# Based on ./gatekeeper/Dockerfile
FROM registry.access.redhat.com/ubi9/go-toolset:9.8-1789040808@sha256:685ccca486cc2c82b0818d835abecb1aed7a396e76ba416cfc47c28067f5d365 as builder
USER 0
COPY drift-detection/detector.sh /detector.sh
# Check to see if we need to react to any uptream changes
COPY drift-cache /drift-cache
WORKDIR /tmp
COPY gatekeeper/Dockerfile .
RUN /detector.sh ./Dockerfile /drift-cache/gatekeeper/Dockerfile

ENV LDFLAGS="-X github.com/open-policy-agent/gatekeeper/v3/pkg/version.Version=v3.21.1" \
    GO111MODULE=on \
    CGO_ENABLED=1

WORKDIR /go/src/github.com/open-policy-agent/gatekeeper
COPY gatekeeper .

RUN go build -mod vendor -a -ldflags "${LDFLAGS}" -o manager

FROM registry.access.redhat.com/ubi9/ubi-minimal:9.8-1791279563@sha256:5ed244b62bbf4095080144d9d35eb8fcd3d39a9801f94aadd63b9d10978a01ae
WORKDIR /
COPY --from=builder /go/src/github.com/open-policy-agent/gatekeeper/manager .
USER 65532:65532
ENTRYPOINT ["/manager"]