# Based on ./gatekeeper-operator/Dockerfile
# Build the manager binary
FROM registry.access.redhat.com/ubi9/go-toolset:9.8-1787774815 as builder
USER 0
COPY drift-detection/detector.sh /detector.sh
# Check to see if we need to react to any uptream changes
COPY drift-cache /drift-cache
WORKDIR /tmp
# gatekeeper-operator/Dockerfile is a symlink to build/Dockerfile upstream; compare the real file
COPY gatekeeper-operator/build/Dockerfile .
RUN /detector.sh ./Dockerfile /drift-cache/gatekeeper-operator/Dockerfile

ENV VERSION_PKG="github.com/stolostron/gatekeeper-operator/pkg/version"
ENV LDFLAGS="-X ${VERSION_PKG}.gitVersion=v3.21.0 \
             -X ${VERSION_PKG}.gitCommit=873a9c7ef2c98fe8e9e7f9d5b99e4cd5c49cc00b \
             -X ${VERSION_PKG}.gitTreeState=clean \
             -X ${VERSION_PKG}.buildDate="

WORKDIR /workspace
# Copy the Go Modules manifests
COPY gatekeeper-operator/go.mod go.mod
COPY gatekeeper-operator/go.sum go.sum
# cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
RUN go mod download

# Copy the go source
COPY gatekeeper-operator/main.go main.go
COPY gatekeeper-operator/api/ api/
COPY gatekeeper-operator/controllers/ controllers/
COPY gatekeeper-operator/pkg/ pkg/

# Build
RUN CGO_ENABLED=1 go build -a -ldflags "${LDFLAGS}$(date -u +'%Y-%m-%dT%H:%M:%SZ')" -o manager main.go

# Use distroless as minimal base image to package the manager binary
# Refer to https://github.com/GoogleContainerTools/distroless for more details
FROM registry.access.redhat.com/ubi9/ubi-minimal:latest
WORKDIR /
COPY --from=builder /workspace/manager .
RUN microdnf -y update && microdnf -y clean all
USER 65532:65532

ENTRYPOINT ["/manager"]
