# Based on ./gatekeeper/Dockerfile
FROM registry.access.redhat.com/ubi9/go-toolset:9.8-1790174511@sha256:0a4666f7a4eb0644c97a73cba198eb268691b270d97831822689e7a2088f87be as builder
USER 0
COPY drift-detection/detector.sh /detector.sh
# Check to see if we need to react to any uptream changes
COPY drift-cache /drift-cache
WORKDIR /tmp
COPY gatekeeper/Dockerfile .
RUN /detector.sh ./Dockerfile /drift-cache/gatekeeper/Dockerfile

ENV LDFLAGS="-X github.com/open-policy-agent/gatekeeper/v3/pkg/version.Version=v3.21.1" \
    GO111MODULE=on \
    CGO_ENABLED=1

WORKDIR /go/src/github.com/open-policy-agent/gatekeeper
COPY gatekeeper .

RUN go build -mod vendor -a -ldflags "${LDFLAGS}" -o manager

FROM registry.access.redhat.com/ubi9/ubi-minimal:9.8-1789546276@sha256:7b8e25a1b56ca4d00219198f3b5b51a3e1693a5c4f5369c5e190d7d6cb3f980e
WORKDIR /
COPY --from=builder /go/src/github.com/open-policy-agent/gatekeeper/manager .
USER 65532:65532
ENTRYPOINT ["/manager"]