# Based on ./gatekeeper-operator/bundle.Dockerfile
FROM registry.access.redhat.com/ubi9/python-311@sha256:a0bdb55576fc5b8d6704279307817828ef027e1065533ceba133fe9516003a6c as builder-runner
COPY requirements.txt .
RUN pip3 install --no-deps --require-hashes -r requirements.txt

# Use a new stage to enable caching of the package installations for local development
FROM builder-runner as builder

USER 0
COPY bundle-hack .
COPY gatekeeper-operator/bundle/manifests /manifests/
COPY gatekeeper-operator/bundle/metadata /metadata/

RUN ./update_bundle.sh

FROM scratch

# Core bundle labels.
LABEL operators.operatorframework.io.bundle.mediatype.v1=registry+v1
LABEL operators.operatorframework.io.bundle.manifests.v1=manifests/
LABEL operators.operatorframework.io.bundle.metadata.v1=metadata/
LABEL operators.operatorframework.io.bundle.package.v1=gatekeeper-operator-product
LABEL operators.operatorframework.io.bundle.channels.v1=stable,3.21
LABEL operators.operatorframework.io.bundle.channel.default.v1=stable
LABEL operators.operatorframework.io.metrics.builder=operator-sdk-v1.34.1
LABEL operators.operatorframework.io.metrics.mediatype.v1=metrics+v1
LABEL operators.operatorframework.io.metrics.project_layout=go.kubebuilder.io/v3

# Labels for testing.
LABEL operators.operatorframework.io.test.mediatype.v1=scorecard+v1
LABEL operators.operatorframework.io.test.config.v1=tests/scorecard/

# Copy files to locations specified by labels.
COPY --from=builder /manifests /manifests/
COPY --from=builder /metadata /metadata/
COPY gatekeeper-operator/bundle/tests/scorecard /tests/scorecard/
