apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/konflux-ci/olm-operator-konflux-sample?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "main" && (".tekton/single-arch-build-pipeline.yaml".pathChanged() || ".tekton/gatekeeper-operator-bundle-pull-request.yaml".pathChanged()
      || ".tekton/gatekeeper-operator-bundle-push.yaml".pathChanged() || "Containerfile.gatekeeper-operator-bundle".pathChanged()
      || "gatekeeper-operator".pathChanged() || "bundle-hack/***".pathChanged())
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: olm-operator
    appstudio.openshift.io/component: gatekeeper-operator-bundle
    pipelines.appstudio.openshift.io/type: build
  name: gatekeeper-operator-bundle-on-push
  namespace: konflux-samples-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/konflux-samples-tenant/olm-operator/gatekeeper-operator-bundle:{{revision}}
  - name: dockerfile
    value: Containerfile.gatekeeper-operator-bundle
  - name: hermetic
    value: "false"
  pipelineRef:
    name: single-arch-build-pipeline
  taskRunTemplate:
    serviceAccountName: build-pipeline-gatekeeper-operator-bundle
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
