apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/konflux-ci/olm-operator-konflux-sample?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "main" && ( "v4.22/***".pathChanged() || ".tekton/fbc-build-pipeline.yaml".pathChanged() || ".tekton/gatekeeper-fbc-v422-pull-request.yaml".pathChanged() )
  creationTimestamp:
  labels:
    appstudio.openshift.io/application: olm-operator-fbc-v422
    appstudio.openshift.io/component: gatekeeper-fbc-v422
    pipelines.appstudio.openshift.io/type: build
  name: gatekeeper-fbc-v422-on-pull-request
  namespace: konflux-samples-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/konflux-samples-tenant/olm-operator-fbc-v422/gatekeeper-fbc-v422:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: build-platforms
    value:
    - linux/x86_64
  - name: dockerfile
    value: Containerfile.catalog
  - name: path-context
    value: v4.22
  - name: opm-args
    value:
    - alpha
    - render-template
    - basic
    - "--migrate-level=bundle-object-to-csv-metadata"
    - "v4.22/catalog-template.yaml"
  - name: opm-output-path
    value: "v4.22/catalog/gatekeeper-operator-product/catalog.json"
  pipelineRef:
    name: fbc-build-pipeline
  taskRunTemplate:
    serviceAccountName: build-pipeline-gatekeeper-fbc-v422
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
