apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/konflux-ci/olm-operator-konflux-sample?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "main" && 
      (".tekton/multi-arch-build-pipeline.yaml".pathChanged() || 
      ".tekton/gatekeeper-pull-request.yaml".pathChanged() || 
      ".tekton/gatekeeper-push.yaml".pathChanged() ||
      "gatekeeper".pathChanged())
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: olm-operator
    appstudio.openshift.io/component: gatekeeper
    pipelines.appstudio.openshift.io/type: build
  name: gatekeeper-on-pull-request
  namespace: konflux-samples-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/konflux-samples-tenant/olm-operator/gatekeeper:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: dockerfile
    value: Containerfile.gatekeeper
  - name: enable-amd64-build
    value: "false"
  - name: enable-arm64-build
    value: "false"
  - name: enable-ppc64le-build
    value: "false"
  - name: enable-s390x-build
    value: "true"
  pipelineRef:
    name: multi-arch-build-pipeline
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'