apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: single-arch-build-pipeline
spec:
  tasks:
  - name: init
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: init
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-init:0.4@sha256:b797dd453ddad669365de6de4649e3a9e37e77aa26eb9862ca079a36cbfe64a4
      - name: kind
        value: task
    params:
    - name: image-url
      value: "$(params.output-image)"
    - name: rebuild
      value: "$(params.rebuild)"
    - name: skip-checks
      value: "$(params.skip-checks)"
    - name: enable-cache-proxy
      value: $(params.enable-cache-proxy)
  - name: clone-repository
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: git-clone-oci-ta
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-git-clone-oci-ta:0.1@sha256:13d49df7dc9ae301627e45f95a236011422996152f1bea46cd60217b0f057407
      - name: kind
        value: task
    when:
    - input: "$(tasks.init.results.build)"
      operator: in
      values:
      - 'true'
    runAfter:
    - init
    params:
    - name: url
      value: "$(params.git-url)"
    - name: revision
      value: "$(params.revision)"
    - name: ociStorage
      value: "$(params.output-image).git"
    - name: ociArtifactExpiresAfter
      value: "$(params.image-expires-after)"
    workspaces:
    - name: basic-auth
      workspace: git-auth
  - name: prefetch-dependencies
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: prefetch-dependencies-oci-ta
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-prefetch-dependencies-oci-ta:0.3@sha256:1b209c0d93e52e418f3e6cd4b4fd915a84e4bd7f68e1cfd0d6446133540d7f43
      - name: kind
        value: task
    params:
    - name: input
      value: "$(params.prefetch-input)"
    - name: hermetic
      value: "$(params.hermetic)"
    - name: dev-package-managers
      value: $(params.prefetch-dev-package-managers-enabled)
    - name: SOURCE_ARTIFACT
      value: $(tasks.clone-repository.results.SOURCE_ARTIFACT)
    - name: ociStorage
      value: $(params.output-image).prefetch
    - name: ociArtifactExpiresAfter
      value: $(params.image-expires-after)
    - name: enable-package-registry-proxy
      value: $(params.enable-package-registry-proxy)
  - name: build-container
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: buildah-oci-ta
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-buildah-oci-ta:0.9@sha256:681d9f65a7f50cb260ee576ccab551e11d63c549f1e1ef3d201da3c112855bd6
      - name: kind
        value: task
    runAfter:
    - clone-repository
    when:
    - input: "$(tasks.init.results.build)"
      operator: in
      values:
      - 'true'
    params:
    - name: IMAGE
      value: "$(params.output-image)"
    - name: DOCKERFILE
      value: "$(params.dockerfile)"
    - name: CONTEXT
      value: "$(params.path-context)"
    - name: HERMETIC
      value: "$(params.hermetic)"
    - name: PREFETCH_INPUT
      value: "$(params.prefetch-input)"
    - name: IMAGE_EXPIRES_AFTER
      value: "$(params.image-expires-after)"
    - name: COMMIT_SHA
      value: "$(tasks.clone-repository.results.commit)"
    - name: SOURCE_ARTIFACT
      value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
    - name: CACHI2_ARTIFACT
      value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)
    - name: BUILDAH_FORMAT
      value: $(params.buildah-format)
    - name: HTTP_PROXY
      value: $(tasks.init.results.http-proxy)
    - name: NO_PROXY
      value: $(tasks.init.results.no-proxy)
  - name: build-source-image
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: source-build-oci-ta
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-source-build-oci-ta:0.3@sha256:0917cfc7772e82cb8e74743c2104f43bcf2596aceafe87eec6fce69a8cac5f06
      - name: kind
        value: task
    when:
    - input: "$(tasks.init.results.build)"
      operator: in
      values:
      - 'true'
    - input: "$(params.build-source-image)"
      operator: in
      values:
      - 'true'
    runAfter:
    - build-container
    params:
    - name: BINARY_IMAGE
      value: "$(tasks.build-container.results.IMAGE_URL)"
    - name: SOURCE_ARTIFACT
      value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
    - name: CACHI2_ARTIFACT
      value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)
    - name: BINARY_IMAGE_DIGEST
      value: $(tasks.build-container.results.IMAGE_DIGEST)
  - name: deprecated-base-image-check
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: deprecated-image-check
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-deprecated-image-check:0.5@sha256:5ff16b7e6b4a8aa1adb352e74b9f831f77ff97bafd1b89ddb0038d63335f1a67
      - name: kind
        value: task
    when:
    - input: "$(params.skip-checks)"
      operator: in
      values:
      - 'false'
    runAfter:
    - build-container
    params:
    - name: IMAGE_URL
      value: $(tasks.build-container.results.IMAGE_URL)
    - name: IMAGE_DIGEST
      value: $(tasks.build-container.results.IMAGE_DIGEST)
  - name: clair-scan
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: clair-scan
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-clair-scan:0.3@sha256:cd49cdea7e5403a87c4774bd8ea10bc4e6aeb83841ff490cbe42b782779513a7
      - name: kind
        value: task
    when:
    - input: "$(params.skip-checks)"
      operator: in
      values:
      - 'false'
    runAfter:
    - build-container
    params:
    - name: image-digest
      value: "$(tasks.build-container.results.IMAGE_DIGEST)"
    - name: image-url
      value: "$(tasks.build-container.results.IMAGE_URL)"
  - name: ecosystem-cert-preflight-checks
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: ecosystem-cert-preflight-checks
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-ecosystem-cert-preflight-checks:0.2@sha256:2468c01818fbaad2235e4fca438f28e847260e3e354cf5a441bbd671684af2db
      - name: kind
        value: task
    when:
    - input: "$(params.skip-checks)"
      operator: in
      values:
      - 'false'
    runAfter:
    - build-container
    params:
    - name: image-url
      value: "$(tasks.build-container.results.IMAGE_URL)"
  - name: sast-snyk-check
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: sast-snyk-check-oci-ta
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-sast-snyk-check-oci-ta:0.4@sha256:8f3ecbeaff579e41b8278f82d7fabac27845db17a8e687ea6c510c0c9aceabbb
      - name: kind
        value: task
    when:
    - input: "$(params.skip-checks)"
      operator: in
      values:
      - 'false'
    runAfter:
    - build-container
    params:
    - name: SOURCE_ARTIFACT
      value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
    - name: image-digest
      value: "$(tasks.build-container.results.IMAGE_DIGEST)"
    - name: image-url
      value: "$(tasks.build-container.results.IMAGE_URL)"
  - name: clamav-scan
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: clamav-scan
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-clamav-scan:0.3@sha256:171eca520b545a0c860c6d59249796ffe5db5be1dab87f3a328fc5ef1fd68af2
      - name: kind
        value: task
    when:
    - input: "$(params.skip-checks)"
      operator: in
      values:
      - 'false'
    runAfter:
    - build-container
    params:
    - name: image-digest
      value: "$(tasks.build-container.results.IMAGE_DIGEST)"
    - name: image-url
      value: "$(tasks.build-container.results.IMAGE_URL)"
  - name: sbom-json-check
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: sbom-json-check
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-sbom-json-check:0.2@sha256:83127520667f47050e52c5fddd7cc1fd6bfc1bffe52964da882565ce304f54bd
      - name: kind
        value: task
    when:
    - input: "$(params.skip-checks)"
      operator: in
      values:
      - 'false'
    runAfter:
    - build-container
    params:
    - name: IMAGE_URL
      value: "$(tasks.build-container.results.IMAGE_URL)"
    - name: IMAGE_DIGEST
      value: "$(tasks.build-container.results.IMAGE_DIGEST)"
  params:
  - name: git-url
    type: string
    description: Source Repository URL
  - name: revision
    type: string
    description: Revision of the Source Repository
    default: ''
  - name: output-image
    type: string
    description: Fully Qualified Output Image
  - name: path-context
    type: string
    description: Path to the source code of an application's component from where to build image.
    default: "."
  - name: dockerfile
    type: string
    description: Path to the Dockerfile inside the context specified by parameter path-context
    default: Dockerfile
  - name: rebuild
    type: string
    description: Force rebuild image
    default: 'false'
  - default: "false"
    description: Skip checks against built image
    name: skip-checks
    type: string
  - default: "false"
    description: Execute the build with network isolation
    name: hermetic
    type: string
  - default: ''
    description: Build dependencies to be prefetched by Cachi2
    name: prefetch-input
    type: string
  - default: "false"
    description: Enable dev-package-managers in prefetch task
    name: prefetch-dev-package-managers-enabled
    type: string
  - name: image-expires-after
    description: Image tag expiration time, time values could be something like 1h, 2d, 3w for hours, days, and weeks, respectively.
    default: ''
  - name: build-source-image
    type: string
    description: Build a source image.
    default: 'false'
  - name: buildah-format
    default: docker
    type: string
    description: The format for the resulting image's mediaType. Valid values are oci or docker.
  - name: enable-cache-proxy
    default: 'false'
    description: Enable cache proxy configuration
    type: string
  - name: enable-package-registry-proxy
    default: 'true'
    description: Use the package registry proxy when prefetching dependencies
    type: string
  workspaces:
  - name: git-auth
    optional: true
  results:
  - name: IMAGE_URL
    description: ''
    value: "$(tasks.build-container.results.IMAGE_URL)"
  - name: IMAGE_DIGEST
    description: ''
    value: "$(tasks.build-container.results.IMAGE_DIGEST)"
  - name: CHAINS-GIT_URL
    description: ''
    value: "$(tasks.clone-repository.results.url)"
  - name: CHAINS-GIT_COMMIT
    description: ''
    value: "$(tasks.clone-repository.results.commit)"
  finally:
  - name: show-sbom
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: show-sbom
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-show-sbom:0.1@sha256:a7346ed61237db4f82ff782e0c9e8b30536e0e67b907ad600341a6d192e80012
      - name: kind
        value: task
    params:
    - name: IMAGE_URL
      value: "$(tasks.build-container.results.IMAGE_URL)"
  - name: show-summary
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: summary
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-summary:0.2@sha256:e1b8e42962b0c6d9ebe95f3709c34ae5e1569b73941a79654248e0af55eb3ff9
      - name: kind
        value: task
    params:
    - name: pipelinerun-name
      value: "$(context.pipelineRun.name)"
    - name: git-url
      value: "$(tasks.clone-repository.results.url)?rev=$(tasks.clone-repository.results.commit)"
    - name: image-url
      value: "$(params.output-image)"
    - name: build-task-status
      value: "$(tasks.build-container.status)"
