apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: single-arch-build-pipeline
spec:
    tasks:
    - name: init
      taskRef:
        resolver: bundles
        params:
        - name: name
          value: init
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-init:0.2@sha256:7a24924417260b7094541caaedd2853dc8da08d4bb0968f710a400d3e8062063
        - name: kind
          value: task
      params:
      - name: image-url
        value: "$(params.output-image)"
      - name: rebuild
        value: "$(params.rebuild)"
      - name: skip-checks
        value: "$(params.skip-checks)"
    - name: clone-repository
      taskRef:
        resolver: bundles
        params:
        - name: name
          value: git-clone-oci-ta
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-git-clone-oci-ta:0.1@sha256:8ecf57d5a6697ce709bee65b62781efe79a10b0c2b95e05576442b67fbd61744
        - name: kind
          value: task
      when:
      - input: "$(tasks.init.results.build)"
        operator: in
        values:
        - 'true'
      runAfter:
      - init
      params:
      - name: url
        value: "$(params.git-url)"
      - name: revision
        value: "$(params.revision)"
      - name: ociStorage
        value: "$(params.output-image).git"
      - name: ociArtifactExpiresAfter
        value: "$(params.image-expires-after)"
      workspaces:
      - name: basic-auth
        workspace: git-auth
    - name: prefetch-dependencies
      taskRef:
        resolver: bundles
        params:
        - name: name
          value: prefetch-dependencies-oci-ta
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-prefetch-dependencies-oci-ta:0.2@sha256:d48c621ae828a3cbca162e12ec166210d2d77a7ba23b0e5d60c4a1b94491adeb
        - name: kind
          value: task
      params:
      - name: input
        value: "$(params.prefetch-input)"
      - name: hermetic
        value: "$(params.hermetic)"
      - name: dev-package-managers
        value: $(params.prefetch-dev-package-managers-enabled)
      - name: SOURCE_ARTIFACT
        value: $(tasks.clone-repository.results.SOURCE_ARTIFACT)
      - name: ociStorage
        value: $(params.output-image).prefetch
      - name: ociArtifactExpiresAfter
        value: $(params.image-expires-after)
    - name: build-container
      taskRef:
        resolver: bundles
        params:
        - name: name
          value: buildah-oci-ta
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-buildah-oci-ta:0.4@sha256:6ac9d16f598c14a4b56e662eccda0a438e94aa8f87dd27a3ea0ff1abc6e00c66
        - name: kind
          value: task
      runAfter:
        - clone-repository
      when:
      - input: "$(tasks.init.results.build)"
        operator: in
        values:
        - 'true'
      params:
      - name: IMAGE
        value: "$(params.output-image)"
      - name: DOCKERFILE
        value: "$(params.dockerfile)"
      - name: CONTEXT
        value: "$(params.path-context)"
      - name: HERMETIC
        value: "$(params.hermetic)"
      - name: PREFETCH_INPUT
        value: "$(params.prefetch-input)"
      - name: IMAGE_EXPIRES_AFTER
        value: "$(params.image-expires-after)"
      - name: COMMIT_SHA
        value: "$(tasks.clone-repository.results.commit)"
      - name: SOURCE_ARTIFACT
        value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
      - name: CACHI2_ARTIFACT
        value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)
    - name: build-source-image
      taskRef:
        resolver: bundles
        params:
        - name: name
          value: source-build-oci-ta
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-source-build-oci-ta:0.2@sha256:56fa2cbfc04bad4765b7fe1fa8022587f4042d4e8533bb5f65311d46b43226ee
        - name: kind
          value: task
      when:
      - input: "$(tasks.init.results.build)"
        operator: in
        values:
        - 'true'
      - input: "$(params.build-source-image)"
        operator: in
        values:
        - 'true'
      runAfter:
      - build-container
      params:
      - name: BINARY_IMAGE
        value: "$(params.output-image)"
      - name: SOURCE_ARTIFACT
        value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
      - name: CACHI2_ARTIFACT
        value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)
    - name: deprecated-base-image-check
      taskRef:
        resolver: bundles
        params:
        - name: name
          value: deprecated-image-check
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-deprecated-image-check:0.5@sha256:ecd33669676b3a193ff4c2c6223cb912cc1b0cf5cc36e080eaec7718500272cf
        - name: kind
          value: task
      when:
      - input: "$(params.skip-checks)"
        operator: in
        values:
        - 'false'
      runAfter:
      - build-container
      params:
      - name: IMAGE_URL
        value: $(tasks.build-container.results.IMAGE_URL)
      - name: IMAGE_DIGEST
        value: $(tasks.build-container.results.IMAGE_DIGEST)
    - name: clair-scan
      taskRef:
        resolver: bundles
        params:
        - name: name
          value: clair-scan
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-clair-scan:0.2@sha256:878ae247ffc58d95a9ac68e4d658ef91ef039363e03e65a386bc0ead02d9d7d8
        - name: kind
          value: task
      when:
      - input: "$(params.skip-checks)"
        operator: in
        values:
        - 'false'
      runAfter:
      - build-container
      params:
      - name: image-digest
        value: "$(tasks.build-container.results.IMAGE_DIGEST)"
      - name: image-url
        value: "$(tasks.build-container.results.IMAGE_URL)"
    - name: ecosystem-cert-preflight-checks
      taskRef:
        resolver: bundles
        params:
        - name: name
          value: ecosystem-cert-preflight-checks
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-ecosystem-cert-preflight-checks:0.2@sha256:1157c6ac9805af8b8874e4b8d68d2403d99e1c007f63623566b5d848b27c1826
        - name: kind
          value: task
      when:
      - input: "$(params.skip-checks)"
        operator: in
        values:
        - 'false'
      runAfter:
      - build-container
      params:
      - name: image-url
        value: "$(tasks.build-container.results.IMAGE_URL)"
    - name: sast-snyk-check
      taskRef:
        resolver: bundles
        params:
        - name: name
          value: sast-snyk-check-oci-ta
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-sast-snyk-check-oci-ta:0.4@sha256:89aead32dc21404e4e0913be9668bdd2eea795db3e4caa762fb619044e479cb8
        - name: kind
          value: task
      when:
      - input: "$(params.skip-checks)"
        operator: in
        values:
        - 'false'
      runAfter:
      - build-container
      params:
      - name: SOURCE_ARTIFACT
        value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
      - name: image-digest
        value: "$(tasks.build-container.results.IMAGE_DIGEST)"
      - name: image-url
        value: "$(tasks.build-container.results.IMAGE_URL)"
    - name: clamav-scan
      taskRef:
        resolver: bundles
        params:
        - name: name
          value: clamav-scan
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-clamav-scan:0.2@sha256:24182598bf5161c4007988a7236e240f361c77a0a9b6973a6712dbae50d296bc
        - name: kind
          value: task
      when:
      - input: "$(params.skip-checks)"
        operator: in
        values:
        - 'false'
      runAfter:
      - build-container
      params:
      - name: image-digest
        value: "$(tasks.build-container.results.IMAGE_DIGEST)"
      - name: image-url
        value: "$(tasks.build-container.results.IMAGE_URL)"
    - name: sbom-json-check
      taskRef:
        resolver: bundles
        params:
        - name: name
          value: sbom-json-check
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-sbom-json-check:0.2@sha256:09b9895fb4195c18cd7529049f89b497021d14137bc0a3f7d747a4291d4a1ace
        - name: kind
          value: task
      when:
      - input: "$(params.skip-checks)"
        operator: in
        values:
        - 'false'
      runAfter:
      - build-container
      params:
      - name: IMAGE_URL
        value: "$(tasks.build-container.results.IMAGE_URL)"
      - name: IMAGE_DIGEST
        value: "$(tasks.build-container.results.IMAGE_DIGEST)"
    params:
    - name: git-url
      type: string
      description: Source Repository URL
    - name: revision
      type: string
      description: Revision of the Source Repository
      default: ''
    - name: output-image
      type: string
      description: Fully Qualified Output Image
    - name: path-context
      type: string
      description: Path to the source code of an application's component from where to
        build image.
      default: "."
    - name: dockerfile
      type: string
      description: Path to the Dockerfile inside the context specified by parameter path-context
      default: Dockerfile
    - name: rebuild
      type: string
      description: Force rebuild image
      default: 'false'
    - default: "false"
      description: Skip checks against built image
      name: skip-checks
      type: string
    - default: "false"
      description: Execute the build with network isolation
      name: hermetic
      type: string
    - default: ''
      description: Build dependencies to be prefetched by Cachi2
      name: prefetch-input
      type: string
    - default: "false"
      description: Enable dev-package-managers in prefetch task
      name: prefetch-dev-package-managers-enabled
      type: string
    - name: image-expires-after
      description: Image tag expiration time, time values could be something like 1h,
        2d, 3w for hours, days, and weeks, respectively.
      default: ''
    - name: build-source-image
      type: string
      description: Build a source image.
      default: 'false'
    workspaces:
    - name: git-auth
      optional: true
    results:
    - name: IMAGE_URL
      description: ''
      value: "$(tasks.build-container.results.IMAGE_URL)"
    - name: IMAGE_DIGEST
      description: ''
      value: "$(tasks.build-container.results.IMAGE_DIGEST)"
    - name: CHAINS-GIT_URL
      description: ''
      value: "$(tasks.clone-repository.results.url)"
    - name: CHAINS-GIT_COMMIT
      description: ''
      value: "$(tasks.clone-repository.results.commit)"
    finally:
    - name: show-sbom
      taskRef:
        resolver: bundles
        params:
        - name: name
          value: show-sbom
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-show-sbom:0.1@sha256:002f7c8c1d2f9e09904035da414aba1188ae091df0ea9532cd997be05e73d594
        - name: kind
          value: task
      params:
      - name: IMAGE_URL
        value: "$(tasks.build-container.results.IMAGE_URL)"
    - name: show-summary
      taskRef:
        resolver: bundles
        params:
        - name: name
          value: summary
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-summary:0.2@sha256:76075b709fa06ed824cbc84f41448b397b85bfde1cf9809395ba6d286f5b7cbd
        - name: kind
          value: task
      params:
      - name: pipelinerun-name
        value: "$(context.pipelineRun.name)"
      - name: git-url
        value: "$(tasks.clone-repository.results.url)?rev=$(tasks.clone-repository.results.commit)"
      - name: image-url
        value: "$(params.output-image)"
      - name: build-task-status
        value: "$(tasks.build-container.status)"
