apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: single-arch-build-pipeline
spec:
    tasks:
    - name: init
      taskRef:
        resolver: bundles
        params:
        - name: name
          value: init
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-init:0.2@sha256:0523b51c28375a3f222da91690e22eff11888ebc98a0c73c468af44762265c69
        - name: kind
          value: task
      params:
      - name: image-url
        value: "$(params.output-image)"
      - name: rebuild
        value: "$(params.rebuild)"
      - name: skip-checks
        value: "$(params.skip-checks)"
    - name: clone-repository
      taskRef:
        resolver: bundles
        params:
        - name: name
          value: git-clone-oci-ta
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-git-clone-oci-ta:0.1@sha256:4bf48d038ff12d25bdeb5ab3e98dc2271818056f454c83d7393ebbd413028147
        - name: kind
          value: task
      when:
      - input: "$(tasks.init.results.build)"
        operator: in
        values:
        - 'true'
      runAfter:
      - init
      params:
      - name: url
        value: "$(params.git-url)"
      - name: revision
        value: "$(params.revision)"
      - name: ociStorage
        value: "$(params.output-image).git"
      - name: ociArtifactExpiresAfter
        value: "$(params.image-expires-after)"
      workspaces:
      - name: basic-auth
        workspace: git-auth
    - name: prefetch-dependencies
      taskRef:
        resolver: bundles
        params:
        - name: name
          value: prefetch-dependencies-oci-ta
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-prefetch-dependencies-oci-ta:0.1@sha256:30c903144e8c8d8c65fb6ec40dd3ff737091609f96fa9f326c047f71242dade4
        - name: kind
          value: task
      params:
      - name: input
        value: "$(params.prefetch-input)"
      - name: hermetic
        value: "$(params.hermetic)"
      - name: dev-package-managers
        value: $(params.prefetch-dev-package-managers-enabled)
      - name: SOURCE_ARTIFACT
        value: $(tasks.clone-repository.results.SOURCE_ARTIFACT)
      - name: ociStorage
        value: $(params.output-image).prefetch
      - name: ociArtifactExpiresAfter
        value: $(params.image-expires-after)
    - name: build-container
      taskRef:
        resolver: bundles
        params:
        - name: name
          value: buildah-oci-ta
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-buildah-oci-ta:0.2@sha256:2d99cd4a5ecec47ba3b4c0a9ad071ca2aa01864906ebcdcfc9686cdc60323e0f
        - name: kind
          value: task
      runAfter:
        - clone-repository
      when:
      - input: "$(tasks.init.results.build)"
        operator: in
        values:
        - 'true'
      params:
      - name: IMAGE
        value: "$(params.output-image)"
      - name: DOCKERFILE
        value: "$(params.dockerfile)"
      - name: CONTEXT
        value: "$(params.path-context)"
      - name: HERMETIC
        value: "$(params.hermetic)"
      - name: PREFETCH_INPUT
        value: "$(params.prefetch-input)"
      - name: IMAGE_EXPIRES_AFTER
        value: "$(params.image-expires-after)"
      - name: COMMIT_SHA
        value: "$(tasks.clone-repository.results.commit)"
      - name: SOURCE_ARTIFACT
        value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
      - name: CACHI2_ARTIFACT
        value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)
    - name: build-source-image
      taskRef:
        resolver: bundles
        params:
        - name: name
          value: source-build
        - name: bundle
          value: quay.io/arewm/task-source-build:modified
        - name: kind
          value: task
      when:
      - input: "$(tasks.init.results.build)"
        operator: in
        values:
        - 'true'
      - input: "$(params.build-source-image)"
        operator: in
        values:
        - 'true'
      runAfter:
      - build-container
      params:
      - name: BINARY_IMAGE
        value: "$(params.output-image)"
      - name: SOURCE_ARTIFACT
        value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
      - name: CACHI2_ARTIFACT
        value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)
    - name: deprecated-base-image-check
      taskRef:
        resolver: bundles
        params:
        - name: name
          value: deprecated-image-check
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-deprecated-image-check:0.4@sha256:5a1a165fa02270f0a947d8a2131ee9d8be0b8e9d34123828c2bef589e504ee84
        - name: kind
          value: task
      when:
      - input: "$(params.skip-checks)"
        operator: in
        values:
        - 'false'
      runAfter:
      - build-container
      params:
      - name: IMAGE_URL
        value: $(tasks.build-container.results.IMAGE_URL)
      - name: IMAGE_DIGEST
        value: $(tasks.build-container.results.IMAGE_DIGEST)
    - name: clair-scan
      taskRef:
        resolver: bundles
        params:
        - name: name
          value: clair-scan
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-clair-scan:0.2@sha256:0a5421111e7092740398691d5bd7c125cc0896f29531d19414bb5724ae41692a
        - name: kind
          value: task
      when:
      - input: "$(params.skip-checks)"
        operator: in
        values:
        - 'false'
      runAfter:
      - build-container
      params:
      - name: image-digest
        value: "$(tasks.build-container.results.IMAGE_DIGEST)"
      - name: image-url
        value: "$(tasks.build-container.results.IMAGE_URL)"
    - name: ecosystem-cert-preflight-checks
      taskRef:
        resolver: bundles
        params:
        - name: name
          value: ecosystem-cert-preflight-checks
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-ecosystem-cert-preflight-checks:0.1@sha256:df8a25a3431a70544172ed4844f9d0c6229d39130633960729f825a031a7dea9
        - name: kind
          value: task
      when:
      - input: "$(params.skip-checks)"
        operator: in
        values:
        - 'false'
      runAfter:
      - build-container
      params:
      - name: image-url
        value: "$(tasks.build-container.results.IMAGE_URL)"
    - name: sast-snyk-check
      taskRef:
        resolver: bundles
        params:
        - name: name
          value: sast-snyk-check-oci-ta
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-sast-snyk-check-oci-ta:0.3@sha256:65a213322ea7c64159e37071d369d74b6378b23403150e29537865cada90f022
        - name: kind
          value: task
      when:
      - input: "$(params.skip-checks)"
        operator: in
        values:
        - 'false'
      runAfter:
      - build-container
      params:
      - name: SOURCE_ARTIFACT
        value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
      - name: image-digest
        value: "$(tasks.build-container.results.IMAGE_DIGEST)"
      - name: image-url
        value: "$(tasks.build-container.results.IMAGE_URL)"
    - name: clamav-scan
      taskRef:
        resolver: bundles
        params:
        - name: name
          value: clamav-scan
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-clamav-scan:0.1@sha256:b4f450f1447b166da671f1d5819ab5a1485083e5c27ab91f7d8b7a2ff994c8c2
        - name: kind
          value: task
      when:
      - input: "$(params.skip-checks)"
        operator: in
        values:
        - 'false'
      runAfter:
      - build-container
      params:
      - name: image-digest
        value: "$(tasks.build-container.results.IMAGE_DIGEST)"
      - name: image-url
        value: "$(tasks.build-container.results.IMAGE_URL)"
    - name: sbom-json-check
      taskRef:
        resolver: bundles
        params:
        - name: name
          value: sbom-json-check
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-sbom-json-check:0.2@sha256:f3f441de3002c5654acdff0553fd54cb1409e6bef6ff68e514d1731c9688b5cc
        - name: kind
          value: task
      when:
      - input: "$(params.skip-checks)"
        operator: in
        values:
        - 'false'
      runAfter:
      - build-container
      params:
      - name: IMAGE_URL
        value: "$(tasks.build-container.results.IMAGE_URL)"
      - name: IMAGE_DIGEST
        value: "$(tasks.build-container.results.IMAGE_DIGEST)"
    params:
    - name: git-url
      type: string
      description: Source Repository URL
    - name: revision
      type: string
      description: Revision of the Source Repository
      default: ''
    - name: output-image
      type: string
      description: Fully Qualified Output Image
    - name: path-context
      type: string
      description: Path to the source code of an application's component from where to
        build image.
      default: "."
    - name: dockerfile
      type: string
      description: Path to the Dockerfile inside the context specified by parameter path-context
      default: Dockerfile
    - name: rebuild
      type: string
      description: Force rebuild image
      default: 'false'
    - default: "false"
      description: Skip checks against built image
      name: skip-checks
      type: string
    - default: "false"
      description: Execute the build with network isolation
      name: hermetic
      type: string
    - default: ''
      description: Build dependencies to be prefetched by Cachi2
      name: prefetch-input
      type: string
    - default: "false"
      description: Enable dev-package-managers in prefetch task
      name: prefetch-dev-package-managers-enabled
      type: string
    - name: java
      type: string
      description: Java build
      default: 'false'
    - name: image-expires-after
      description: Image tag expiration time, time values could be something like 1h,
        2d, 3w for hours, days, and weeks, respectively.
      default: ''
    - name: build-source-image
      type: string
      description: Build a source image.
      default: 'false'
    workspaces:
    - name: git-auth
      optional: true
    results:
    - name: IMAGE_URL
      description: ''
      value: "$(tasks.build-container.results.IMAGE_URL)"
    - name: IMAGE_DIGEST
      description: ''
      value: "$(tasks.build-container.results.IMAGE_DIGEST)"
    - name: CHAINS-GIT_URL
      description: ''
      value: "$(tasks.clone-repository.results.url)"
    - name: CHAINS-GIT_COMMIT
      description: ''
      value: "$(tasks.clone-repository.results.commit)"
    - name: JAVA_COMMUNITY_DEPENDENCIES
      description: ''
      value: "$(tasks.build-container.results.JAVA_COMMUNITY_DEPENDENCIES)"
    finally:
    - name: show-sbom
      taskRef:
        resolver: bundles
        params:
        - name: name
          value: show-sbom
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-show-sbom:0.1@sha256:945a7c9066d3e0a95d3fddb7e8a6992e4d632a2a75d8f3a9bd2ff2fef0ec9aa0
        - name: kind
          value: task
      params:
      - name: IMAGE_URL
        value: "$(tasks.build-container.results.IMAGE_URL)"
    - name: show-summary
      taskRef:
        resolver: bundles
        params:
        - name: name
          value: summary
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-summary:0.2@sha256:870d9a04d9784840a90b7bf6817cd0d0c4edfcda04b1ba1868cae625a3c3bfcc
        - name: kind
          value: task
      params:
      - name: pipelinerun-name
        value: "$(context.pipelineRun.name)"
      - name: git-url
        value: "$(tasks.clone-repository.results.url)?rev=$(tasks.clone-repository.results.commit)"
      - name: image-url
        value: "$(params.output-image)"
      - name: build-task-status
        value: "$(tasks.build-container.status)"